### PR TITLE
update from transformers

### PR DESCRIPTION
**Pull request by MikeLdT**
Transformers now imports loggins from transformer.utils instead of transformer

### CODE REVIEW

**Comment by econabhishek** [comment]
Thanks for this! - I wonder if pegging the version of Transformers to an earlier one makes sense vs trying to keep up with updates of the transformers library - let me think about this more.

**Comment by econabhishek** [comment]
Thanks for sharing this.
Checked this today, this update doesn't seem necessary on the latest stable version 4.34.1. 

.utlils.logging is being imported in the name space in the __init__ file. Both yours and the existing import statements would work.

https://github.com/huggingface/transformers/blob/main/src/transformers/__init__.py

Is there a specific version that is throwing this error? I can edit the setup/requirements file accordingly.

**Comment by MikeLdT** [comment]
I encountered the error for such version in a GCP Workbench notebook, but I tried importing the package in a collab notebook and it runed just fine. Maybe is something specific of GCP VMs

**Review by econabhishek — APPROVED** [review]
Thanks for these - approving the changes. While we don't want to guarantee support on all OS at this stage - this fix is easy and general enough.

**Pull request merged**
